baseurl: /jekyll-cornell-notes

markdown: kramdown
kramdown:
  syntax-highlighter: rouge
highlighter: rouge

include: ["_notes"]

collections:
  notes:
    output: true
  
defaults:
  - scope:
      path: "_notes"
    values:
      layout: note